/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pleystation.view.user;

import java.awt.Frame;
import java.util.List;
import pleystation.model.UserModel;
import pleystation.model.UserModel.UserLevel;
import pleystation.model.controller.UserController;

/**
 *
 * @author Aksal
 */
public class UserDetailsDialog extends javax.swing.JDialog {
    
    private String username;
    private UserController controller;

    /**
     * Creates new form CustomerDetailsDialog
     */
    public UserDetailsDialog(Frame parentFrame, UserController controller) {
        super(parentFrame, true);
        initComponents();
        setLocationRelativeTo(null);
        
        btnDeleteAndCancel.setVisible(false);
        btnEditAndSave.setText("Tambah");
        txtUsername.setEnabled(true);
        txtFullname.setEnabled(true);
        txtPassword.setEnabled(true);
        cbUserLevel.setEnabled(true);
        
        this.controller = controller;
    }

    public UserDetailsDialog(Frame parentFrame, UserController controller, String username) {
        super(parentFrame, true);
        initComponents();
        setLocationRelativeTo(null);
        
        this.username = username;
        this.controller = controller;
        
        UserModel userModel = controller.getUserData(username);
        txtUsername.setText(userModel.getUsername());
        txtFullname.setText(userModel.getFullname());
        cbUserLevel.setSelectedIndex(userModel.getLevel().ordinal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblFullname = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblUserLevel = new javax.swing.JLabel();
        cbUserLevel = new javax.swing.JComboBox<>();
        btnEditAndSave = new javax.swing.JButton();
        btnDeleteAndCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlHeader.setBackground(java.awt.SystemColor.controlHighlight);

        lblTitle.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 51, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Rincian Data");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblUsername.setText("Nama Pengguna");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtUsername.setEnabled(false);

        lblFullname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblFullname.setText("Nama Lengkap");

        txtFullname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtFullname.setEnabled(false);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPassword.setText("Kata Sandi");

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPassword.setEnabled(false);

        lblUserLevel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblUserLevel.setText("Hak Akses");

        cbUserLevel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbUserLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Kasir" }));
        cbUserLevel.setEnabled(false);

        btnEditAndSave.setText("Ubah");
        btnEditAndSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAndSaveActionPerformed(evt);
            }
        });

        btnDeleteAndCancel.setText("Hapus");
        btnDeleteAndCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAndCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblUserLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDeleteAndCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditAndSave, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                .addComponent(txtFullname))
                            .addComponent(cbUserLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullname)
                    .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserLevel)
                    .addComponent(cbUserLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteAndCancel)
                    .addComponent(btnEditAndSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditAndSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAndSaveActionPerformed
        switch(btnEditAndSave.getText()) {
            case "Ubah":
                btnEditAndSave.setText("Simpan");
                btnDeleteAndCancel.setText("Batal");
                
                txtFullname.setEnabled(true);
                txtPassword.setEnabled(true);
                cbUserLevel.setEnabled(true);
                break;
                
            case "Simpan":
                btnEditAndSave.setText("Ubah");
                btnDeleteAndCancel.setText("Hapus");
                controller.updateData(new UserModel(txtUsername.getText(), 
                        txtFullname.getText(), 
                        txtPassword.getText(), 
                        UserLevel.valueOf(cbUserLevel.getSelectedItem().toString())));
                dispose();
                break;
                
            case "Tambah":
                btnDeleteAndCancel.setText("Batal");

                controller.addData(new UserModel(txtUsername.getText(), 
                        txtFullname.getText(), 
                        txtPassword.getText(), 
                        UserLevel.valueOf(cbUserLevel.getSelectedItem().toString())));
                dispose();
                break;
        }
    }//GEN-LAST:event_btnEditAndSaveActionPerformed

    private void btnDeleteAndCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAndCancelActionPerformed
        switch(btnDeleteAndCancel.getText()) {
            case "Hapus":
                btnEditAndSave.setText("Konfirmasi");
                btnDeleteAndCancel.setText("Batal");
                
                controller.deleteUserData(username);
                dispose();
                break;
                
            case "Batal":
                btnEditAndSave.setText("Ubah");
                btnDeleteAndCancel.setText("Hapus");
                break;
        }
    }//GEN-LAST:event_btnDeleteAndCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteAndCancel;
    private javax.swing.JButton btnEditAndSave;
    private javax.swing.JComboBox<String> cbUserLevel;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserLevel;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
