/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pleystation.view.product;

import pleystation.view.customer.*;
import java.awt.Frame;
import pleystation.model.ProductModel;
import pleystation.model.ProductModel.ProductCategory;
import pleystation.model.controller.ProductController;

/**
 *
 * @author Aksal
 */
public class ProductDetailsDialog extends javax.swing.JDialog {
    
    private int product_id;
    private ProductController controller;

    /**
     * Creates new form CustomerDetailsDialog
     */
    public ProductDetailsDialog(Frame parentFrame, ProductController controller) {
        super(parentFrame, true);
        initComponents();
        setLocationRelativeTo(null);
        
        btnDeleteAndCancel.setVisible(false);
        btnEditAndSave.setText("Tambah");
        cbCategory.setEnabled(true);
        txtName.setEnabled(true);
        txtAvailability.setEnabled(true);
        txtRentPrice.setEnabled(true);
        
        this.controller = controller;
    }

    public ProductDetailsDialog(Frame parentFrame, ProductController controller, int product_id) {
        super(parentFrame, true);
        initComponents();
        setLocationRelativeTo(null);
        
        this.product_id = product_id;
        this.controller = controller;
        
        ProductModel productModel = controller.getData(product_id);
        txtProductId.setText(String.valueOf(productModel.getProductId()));
        cbCategory.setSelectedIndex(productModel.getCategory().ordinal());
        txtName.setText(productModel.getName());
        txtAvailability.setText(String.valueOf(productModel.getAvailability()));
        txtRentPrice.setText(String.valueOf(productModel.getRentPrice()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblProductId = new javax.swing.JLabel();
        txtProductId = new javax.swing.JTextField();
        lblCategory = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        btnEditAndSave = new javax.swing.JButton();
        btnDeleteAndCancel = new javax.swing.JButton();
        lblAvailability = new javax.swing.JLabel();
        txtAvailability = new javax.swing.JTextField();
        lblRentPrice = new javax.swing.JLabel();
        txtRentPrice = new javax.swing.JTextField();
        cbCategory = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlHeader.setBackground(java.awt.SystemColor.controlHighlight);

        lblTitle.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 51, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Rincian Data");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lblProductId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblProductId.setText("ID Barang");

        txtProductId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtProductId.setEnabled(false);

        lblCategory.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCategory.setText("Kategori");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtName.setEnabled(false);

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblName.setText("Nama");

        btnEditAndSave.setText("Ubah");
        btnEditAndSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAndSaveActionPerformed(evt);
            }
        });

        btnDeleteAndCancel.setText("Hapus");
        btnDeleteAndCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAndCancelActionPerformed(evt);
            }
        });

        lblAvailability.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblAvailability.setText("Ketersediaan");

        txtAvailability.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtAvailability.setEnabled(false);

        lblRentPrice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblRentPrice.setText("Harga Sewa");

        txtRentPrice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtRentPrice.setEnabled(false);

        cbCategory.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLAYSTATION", "GAME", "ACCESSORIES" }));
        cbCategory.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRentPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProductId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                        .addComponent(cbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnDeleteAndCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditAndSave, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtRentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductId)
                    .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailability)
                    .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRentPrice)
                    .addComponent(txtRentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteAndCancel)
                    .addComponent(btnEditAndSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditAndSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAndSaveActionPerformed
        switch(btnEditAndSave.getText()) {
            case "Ubah":
                btnEditAndSave.setText("Simpan");
                btnDeleteAndCancel.setText("Batal");
                
                cbCategory.setEnabled(true);
                txtName.setEnabled(true);
                txtAvailability.setEnabled(true);
                txtRentPrice.setEnabled(true);
                break;
                
            case "Simpan":
                btnEditAndSave.setText("Ubah");
                btnDeleteAndCancel.setText("Hapus");
                controller.updateData(new ProductModel(Integer.parseInt(txtProductId.getText()), 
                        txtName.getText(), 
                        Integer.parseInt(txtAvailability.getText()), 
                        Integer.parseInt(txtRentPrice.getText()), 
                        ProductCategory.values()[cbCategory.getSelectedIndex()]));
                dispose();
                break;
                
            case "Tambah":
                btnDeleteAndCancel.setText("Batal");

                controller.addData(new ProductModel(0, 
                        txtName.getText(), 
                        Integer.parseInt(txtAvailability.getText()), 
                        Integer.parseInt(txtRentPrice.getText()), 
                        ProductCategory.values()[cbCategory.getSelectedIndex()]));
                dispose();
                break;
        }
    }//GEN-LAST:event_btnEditAndSaveActionPerformed

    private void btnDeleteAndCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAndCancelActionPerformed
        switch(btnDeleteAndCancel.getText()) {
            case "Hapus":
                btnEditAndSave.setText("Konfirmasi");
                btnDeleteAndCancel.setText("Batal");
                
                controller.deleteData(product_id);
                dispose();
                break;
                
            case "Batal":
                btnEditAndSave.setText("Ubah");
                btnDeleteAndCancel.setText("Hapus");
                break;
        }
    }//GEN-LAST:event_btnDeleteAndCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteAndCancel;
    private javax.swing.JButton btnEditAndSave;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblProductId;
    private javax.swing.JLabel lblRentPrice;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtProductId;
    private javax.swing.JTextField txtRentPrice;
    // End of variables declaration//GEN-END:variables
}
