/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pleystation.view.customer;

import java.awt.Frame;
import pleystation.model.CustomerModel;
import pleystation.model.controller.CustomerController;
import pleystation.model.controller.TransactionController;

/**
 *
 * @author Aksal
 */
public class CustomerDetailsDialog extends javax.swing.JDialog {
    
    private int customer_id;
    private CustomerController controller;

    /**
     * Creates new form CustomerDetailsDialog
     */
    public CustomerDetailsDialog(Frame parentFrame, CustomerController controller) {
        super(parentFrame, true);
        initComponents();
        setLocationRelativeTo(null);
        
        btnDeleteAndCancel.setVisible(false);
        btnEditAndSave.setText("Tambah");
        txtName.setEnabled(true);
        txtTelephone.setEnabled(true);
        txtAddress.setEnabled(true);
        lblIsRenting.setVisible(false);
        lblIsRentingValue.setVisible(false);
        
        this.controller = controller;
    }

    public CustomerDetailsDialog(Frame parentFrame, CustomerController controller, int customer_id) {
        super(parentFrame, true);
        initComponents();
        setLocationRelativeTo(null);
        
        this.customer_id = customer_id;
        this.controller = controller;
        
        CustomerModel customerModel = controller.getData(customer_id);
        txtCustomerId.setText(String.valueOf(customerModel.getCustomerId()));
        txtName.setText(customerModel.getName());
        txtTelephone.setText(customerModel.getTelephone());
        txtAddress.setText(customerModel.getAddress());
        
        if (controller.isRenting(customer_id)) {
            lblIsRentingValue.setText("Ya");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblCustomerId = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        lblTelephone = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        pnlTxtAddress = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnEditAndSave = new javax.swing.JButton();
        btnDeleteAndCancel = new javax.swing.JButton();
        lblIsRentingValue = new javax.swing.JLabel();
        lblIsRenting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlHeader.setBackground(java.awt.SystemColor.controlHighlight);

        lblTitle.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 51, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Rincian Data");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lblCustomerId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCustomerId.setText("ID Penyewa");

        txtCustomerId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCustomerId.setEnabled(false);

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtName.setEnabled(false);

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblName.setText("Nama");

        txtTelephone.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtTelephone.setEnabled(false);

        lblTelephone.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblTelephone.setText("Telepon");

        lblAddress.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblAddress.setText("Alamat");

        pnlTxtAddress.setEnabled(false);

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtAddress.setLineWrap(true);
        txtAddress.setRows(5);
        txtAddress.setWrapStyleWord(true);
        txtAddress.setEnabled(false);
        pnlTxtAddress.setViewportView(txtAddress);

        btnEditAndSave.setText("Ubah");
        btnEditAndSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAndSaveActionPerformed(evt);
            }
        });

        btnDeleteAndCancel.setText("Hapus");
        btnDeleteAndCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAndCancelActionPerformed(evt);
            }
        });

        lblIsRentingValue.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblIsRentingValue.setText("Tidak");

        lblIsRenting.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblIsRenting.setText("Menyewa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIsRenting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTelephone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCustomerId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDeleteAndCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditAndSave, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlTxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIsRentingValue))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerId)
                    .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelephone)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress)
                    .addComponent(pnlTxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsRentingValue)
                    .addComponent(lblIsRenting))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteAndCancel)
                    .addComponent(btnEditAndSave))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditAndSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAndSaveActionPerformed
        switch(btnEditAndSave.getText()) {
            case "Ubah":
                btnEditAndSave.setText("Simpan");
                btnDeleteAndCancel.setText("Batal");
                
                txtName.setEnabled(true);
                txtTelephone.setEnabled(true);
                txtAddress.setEnabled(true);
                break;
                
            case "Simpan":
                btnEditAndSave.setText("Ubah");
                btnDeleteAndCancel.setText("Hapus");
                controller.updateData(new CustomerModel(Integer.parseInt(txtCustomerId.getText()), 
                        txtName.getText(), 
                        txtTelephone.getText(), 
                        txtAddress.getText()));
                dispose();
                break;
                
            case "Tambah":
                btnDeleteAndCancel.setText("Batal");

                controller.addData(new CustomerModel(0, 
                        txtName.getText(), 
                        txtTelephone.getText(), 
                        txtAddress.getText()));
                dispose();
                break;
        }
    }//GEN-LAST:event_btnEditAndSaveActionPerformed

    private void btnDeleteAndCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAndCancelActionPerformed
        switch(btnDeleteAndCancel.getText()) {
            case "Hapus":
                btnEditAndSave.setText("Konfirmasi");
                btnDeleteAndCancel.setText("Batal");
                
                controller.deleteData(customer_id);
                dispose();
                break;
                
            case "Batal":
                btnEditAndSave.setText("Ubah");
                btnDeleteAndCancel.setText("Hapus");
                break;
        }
    }//GEN-LAST:event_btnDeleteAndCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteAndCancel;
    private javax.swing.JButton btnEditAndSave;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblIsRenting;
    private javax.swing.JLabel lblIsRentingValue;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JScrollPane pnlTxtAddress;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
